### ISSUE TITLE
ankitgrover07-recommendations for Denver, CO

### ISSUE THREAD

**Issue by ankitgrover07** [githubteacher/developers-july#18]
# Denver
- [x] Create a branch
- [x] Add a file
- [x] Commit a file
- [x] Open  a Pull request
- [ ] Collaboration with my team
- [ ] Get a +1
- [ ] ship it

@divanathan @baryal @alephzed @bmdangol @baryal @phustondva @JosephWebster

**Comment by phustondva** [comment]
+1 into emoji - type colon for list
