### ISSUE TITLE
kakuls' recommendation for Kanpur, India

### ISSUE THREAD

**Issue by kakuls** [githubteacher/developers-july#8]
# Kanpur, India
- [x] create a branch
- [x] Add a file
- [x] Commit the file
- [x] Open a pull request
- [ ] collaborate with my team 
- [ ] get a :+1:
- [ ] Merge the pull request
- [ ] ✨

**Comment by kakuls** [comment]
hey @FalconDelmi and @ravisubramanian10 do you have any thoughts about how I add to this guide?

**Comment by FalconDelmi** [comment]
I have no idea!
